### Criar novo usuário
POST http://localhost:3333/api/user/create
Content-Type: application/json

{
  "name": "Guilherme Bueno",
  "email": "guilhermebuenoreis@gmail.com",
  "password": "123456"
}

### Enviar magic link por e-mail
POST http://localhost:3333/api/auth/magic-link
Content-Type: application/json

{
  "email": "guilhermebuenoreis@gmail.com"
}
