version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker 
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: axondb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
